import jsPDF from 'jspdf';
import { DetailedAuditResponse } from './accessibilityAudit';

export const generateExecutiveReport = async (
    auditData: DetailedAuditResponse,
    targetUrl: string
) => {
    // Create a new PDF document in portrait mode, A4 size
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    let cursorY = 20;

    // Helper to add text and update cursor
    const addText = (text: string, size: number, isBold = false, x = 20, align: 'left' | 'center' | 'right' = 'left') => {
        doc.setFont("helvetica", isBold ? "bold" : "normal");
        doc.setFontSize(size);
        doc.text(text, x, cursorY, { align });
        cursorY += size * 0.4 + 2; // rough line height
    };

    // --- Header ---
    // A subtle tech background strip
    doc.setFillColor(30, 41, 59); // dark slate 
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    cursorY = 15;
    addText('AKANEXUS ACCESSIBILITY COMPLIANCE', 16, true, pageWidth / 2, 'center');
    cursorY = 25;
    addText('EXECUTIVE AUDIT REPORT', 12, false, pageWidth / 2, 'center');

    cursorY = 50;
    doc.setTextColor(0, 0, 0);

    // --- Meta Info ---
    addText(`Target: ${targetUrl || 'Local Code Component'}`, 12, true);
    addText(`Date: ${new Date().toLocaleDateString()}`, 10, false);
    addText('Required Standard: WCAG 2.1 Level AA (ADA Title II)', 10, false);

    cursorY += 10;

    // --- Readiness Score ---
    doc.setDrawColor(200, 200, 200);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(20, cursorY, pageWidth - 40, 30, 2, 2, 'FD');

    cursorY += 15;
    addText(`${auditData.score}% Compliance`, 24, true, pageWidth / 2, 'center');
    cursorY += 5;

    let assessmentText = 'Requires Immediate Remediation';
    if (auditData.score >= 90) assessmentText = 'Target Achieved (Monitor for Drift)';
    else if (auditData.score >= 70) assessmentText = 'Approaching Compliance (Minor Fixes Needed)';

    addText(assessmentText, 10, false, pageWidth / 2, 'center');
    cursorY += 20;

    // --- Metrics Summary ---
    addText('Executive Summary', 14, true);
    cursorY += 2;

    const metricY = cursorY;
    // Box 1 (Violations)
    doc.rect(20, cursorY, 50, 20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(220, 38, 38); // red
    doc.text(`${auditData.violations.length}`, 45, cursorY + 10, { align: 'center' });
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('VIOLATIONS', 45, cursorY + 16, { align: 'center' });

    // Box 2 (Passes)
    doc.rect(80, cursorY, 50, 20);
    doc.setFontSize(16);
    doc.setTextColor(16, 185, 129); // green
    doc.text(`${auditData.passes}`, 105, cursorY + 10, { align: 'center' });
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('PASSING', 105, cursorY + 16, { align: 'center' });

    // Box 3 (Inapplicable)
    doc.rect(140, cursorY, 50, 20);
    doc.setFontSize(16);
    doc.setTextColor(100, 100, 100); // gray
    doc.text(`${auditData.inapplicable}`, 165, cursorY + 10, { align: 'center' });
    doc.setFontSize(10);
    doc.text('INAPPLICABLE', 165, cursorY + 16, { align: 'center' });

    cursorY += 30;
    doc.setTextColor(0, 0, 0);

    // --- Violations List ---
    if (auditData.violations.length > 0) {
        addText('Identified Violations', 14, true);
        cursorY += 4;

        auditData.violations.forEach((v, index) => {
            // Check for page break
            if (cursorY > 260) {
                doc.addPage();
                cursorY = 20;
            }

            doc.setFont("helvetica", "bold");
            doc.setFontSize(10);
            doc.text(`${index + 1}. [${v.impact.toUpperCase()}] ${v.help}`, 20, cursorY);
            cursorY += 6;

            doc.setFont("helvetica", "normal");
            doc.setFontSize(9);

            const lines = doc.splitTextToSize(v.description, pageWidth - 45);
            doc.text(lines, 25, cursorY);
            cursorY += (lines.length * 4) + 2;

            // Draw a small line to separate items
            doc.setDrawColor(230, 230, 230);
            doc.line(25, cursorY, pageWidth - 20, cursorY);
            cursorY += 6;
        });
    } else {
        // No violations
        addText('No automated violations were detected. A manual verification is still recommended.', 10, false);
    }

    // --- Footer ---
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by Akanexus Studio | Page ${i} of ${pageCount}`, pageWidth / 2, 285, { align: 'center' });
    }

    // Download the PDF
    const filename = `Accessibility_Report_${targetUrl ? "URL" : "Local"}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
};
